# Generated by Django 5.2 on 2025-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0002_aluminumuser_delete_aluminumdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminumuser',
            name='email',
            field=models.EmailField(max_length=190, null=True, unique=True),
        ),
    ]
