# Generated by Django 5.2 on 2025-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0003_alter_aluminumuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluminumuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='aluminumuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluminumuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('scrap_team', 'Scrap Team')], default='agent', max_length=20),
        ),
        migrations.AddField(
            model_name='aluminumuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
