# Generated by Django 5.2 on 2025-10-31 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0004_remove_aluminumuser_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('ore_quality', models.FloatField()),
                ('reaction_time', models.FloatField()),
                ('predicted_aluminum', models.FloatField()),
                ('predicted_byproduct', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='aluminumRec.aluminumuser')),
            ],
        ),
    ]
