# Generated by Django 5.2 on 2025-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0005_productionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='bauxite_mass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='caustic_soda_conc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='ore_quality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='predicted_aluminum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='predicted_byproduct',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='reaction_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
