# Generated by Django 5.2 on 2025-11-04 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0006_productionrecord_bauxite_mass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Red Mud', max_length=100)),
                ('quantity_kg', models.FloatField(default=0)),
                ('percent_of_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In Process'), ('used', 'Used')], default='received', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'scrap_team'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='byproduct_tasks', to='aluminumRec.aluminumuser')),
                ('source_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproducts', to='aluminumRec.productionrecord')),
            ],
        ),
    ]
