# Generated by Django 5.2 on 2025-11-10 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminumRec', '0007_byproductrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Red Mud', max_length=100)),
                ('quantity_kg', models.FloatField(default=0)),
                ('percent_of_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In Process'), ('used', 'Used')], default='received', max_length=20)),
                ('source_prediction_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
